services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./node_modules
        target: /app/node_modules
    restart: always
    tty: true
    stdin_open: true
volumes:
  node_modules:
